-- Reset schema
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- Roles Table
CREATE TABLE "Roles" (
  "RoleId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" varchar(50) NOT NULL
);

-- UserProfile Table
CREATE TABLE "UserProfile" (
  "UserId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DisplayName" varchar(100),
  "FirstName" varchar(100),
  "LastName" varchar(100),
  "Email" varchar(255) UNIQUE NOT NULL,
  "AuthId" varchar(255)
);

-- UserRole Table (with unique constraint on UserId, RoleId)
CREATE TABLE "UserRole" (
  "UserRoleId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleId" integer NOT NULL,
  "UserId" integer NOT NULL,
  CONSTRAINT "UQ_UserRole_User_Role" UNIQUE ("UserId", "RoleId")
);

-- Address Table
CREATE TABLE "Address" (
  "AddressId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer NOT NULL,
  "Street" varchar(255) NOT NULL,
  "City" varchar(100) NOT NULL,
  "State" varchar(100),
  "ZipCode" varchar(20) NOT NULL
);

-- UserActivityLog Table
CREATE TABLE "UserActivityLog" (
  "LogId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer,
  "ActivityType" varchar(100) NOT NULL,
  "ActivityDescription" text,
  "LogDate" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);

-- Category Table
CREATE TABLE "Category" (
  "CategoryId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CategoryName" varchar(150) NOT NULL
);

-- Product Table (with CHECK constraints)
CREATE TABLE "Product" (
  "ProductId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ProductName" varchar(255) NOT NULL,
  "Price" decimal(10,2) NOT NULL CHECK ("Price" >= 0),
  "Quantity" integer NOT NULL DEFAULT 0 CHECK ("Quantity" >= 0),
  "CategoryId" integer,
  "IsActive" boolean DEFAULT true,
  "CreatedAt" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);

-- ProductImage Table
CREATE TABLE "ProductImage" (
  "ImageId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ProductId" integer NOT NULL,
  "ImageUrl" text NOT NULL
);

-- ProductReview Table (with CHECK constraint for Rating 1-5)
CREATE TABLE "ProductReview" (
  "ReviewId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ProductId" integer NOT NULL,
  "UserId" integer NOT NULL,
  "Rating" integer CHECK ("Rating" >= 1 AND "Rating" <= 5),
  "ReviewText" text,
  "ReviewDate" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);

-- Coupon Table (with CHECK constraint)
CREATE TABLE "Coupon" (
  "CouponId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CouponCode" varchar(50) UNIQUE NOT NULL,
  "DiscountAmount" decimal(10,2) NOT NULL CHECK ("DiscountAmount" >= 0),
  "ExpiryDate" date NOT NULL,
  "ProductId" integer,
  "CategoryId" integer
);

-- Wishlist Table (with unique constraint on UserId, ProductId)
CREATE TABLE "Wishlist" (
  "WishlistId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer NOT NULL,
  "ProductId" integer NOT NULL,
  CONSTRAINT "UQ_Wishlist_User_Product" UNIQUE ("UserId", "ProductId")
);

-- Cart Table (with unique constraint on UserId, ProductId, and CHECK on Quantity)
CREATE TABLE "Cart" (
  "CartId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer NOT NULL,
  "ProductId" integer NOT NULL,
  "Quantity" integer NOT NULL DEFAULT 1 CHECK ("Quantity" >= 1),
  CONSTRAINT "UQ_Cart_User_Product" UNIQUE ("UserId", "ProductId")
);

-- Orders Table (with CHECK constraint)
CREATE TABLE "Orders" (
  "OrderId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" integer,
  "OrderDate" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "TotalAmount" decimal(10,2) NOT NULL CHECK ("TotalAmount" >= 0)
);

-- OrderItem Table (with CHECK constraints)
CREATE TABLE "OrderItem" (
  "OrderItemId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" integer NOT NULL,
  "ProductId" integer NOT NULL,
  "Quantity" integer NOT NULL CHECK ("Quantity" >= 1),
  "Price" decimal(10,2) NOT NULL CHECK ("Price" >= 0),
  "TotalCost" decimal(10,2) NOT NULL CHECK ("TotalCost" >= 0)
);

-- OrderStatus Table
CREATE TABLE "OrderStatus" (
  "StatusId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" integer NOT NULL,
  "StatusName" varchar(50) NOT NULL,
  "CreatedAt" timestamptz DEFAULT (CURRENT_TIMESTAMP)
);

-- OrderCoupon Table
CREATE TABLE "OrderCoupon" (
  "OrderCouponId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" integer NOT NULL,
  "CouponId" integer
);

-- PaymentInformation Table (with CHECK constraint)
CREATE TABLE "PaymentInformation" (
  "PaymentId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" integer NOT NULL,
  "PaymentAmount" decimal(10,2) NOT NULL CHECK ("PaymentAmount" >= 0),
  "PaymentDate" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "PaymentMethod" varchar(50) NOT NULL
);

-- Foreign Key Constraints
ALTER TABLE "UserRole" ADD FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "UserRole" ADD FOREIGN KEY ("UserId") REFERENCES "UserProfile" ("UserId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Address" ADD FOREIGN KEY ("UserId") REFERENCES "UserProfile" ("UserId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserActivityLog" ADD FOREIGN KEY ("UserId") REFERENCES "UserProfile" ("UserId") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Product" ADD FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ProductImage" ADD FOREIGN KEY ("ProductId") REFERENCES "Product" ("ProductId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ProductReview" ADD FOREIGN KEY ("ProductId") REFERENCES "Product" ("ProductId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ProductReview" ADD FOREIGN KEY ("UserId") REFERENCES "UserProfile" ("UserId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Coupon" ADD FOREIGN KEY ("ProductId") REFERENCES "Product" ("ProductId") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Coupon" ADD FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Wishlist" ADD FOREIGN KEY ("UserId") REFERENCES "UserProfile" ("UserId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Wishlist" ADD FOREIGN KEY ("ProductId") REFERENCES "Product" ("ProductId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Cart" ADD FOREIGN KEY ("UserId") REFERENCES "UserProfile" ("UserId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "Cart" ADD FOREIGN KEY ("ProductId") REFERENCES "Product" ("ProductId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Orders" ADD FOREIGN KEY ("UserId") REFERENCES "UserProfile" ("UserId") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderItem" ADD FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "OrderItem" ADD FOREIGN KEY ("ProductId") REFERENCES "Product" ("ProductId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderStatus" ADD FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderCoupon" ADD FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "OrderCoupon" ADD FOREIGN KEY ("CouponId") REFERENCES "Coupon" ("CouponId") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PaymentInformation" ADD FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
